# Generated by Django 2.0.2 on 2018-10-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReview', '0002_auto_20181008_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='movie_release_date',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
