# Generated by Django 2.0.2 on 2018-10-08 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReview', '0003_movieinfo_movie_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='movie_detail',
            field=models.TextField(default=' ', max_length=500),
            preserve_default=False,
        ),
    ]
