# Generated by Django 2.0.2 on 2018-10-08 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReview', '0005_movieinfo_movie_genere'),
    ]

    operations = [
       
        
        
        migrations.RemoveField(
            model_name='movieinfo',
            name='movie_type',
        ),
    ]
