# Generated by Django 2.0.2 on 2018-10-08 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReview', '0006_auto_20181008_1127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieInfo',
        ),
    ]
