# Generated by Django 2.0.2 on 2018-10-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MovieReview', '0007_delete_movieinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_review', models.CharField(max_length=5)),
                ('movie_name', models.CharField(max_length=200)),
            ],
        ),
    ]
