# Generated by Django 2.0.2 on 2018-10-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReview', '0009_auto_20181008_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
            ],
        ),
    ]
