# Generated by Django 2.0.2 on 2018-10-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReview', '0010_songinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='songinfo',
            name='album_name',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songinfo',
            name='singer_name',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
